export const projects = [
  {
    title: "Travel Agency",
    subtitle: "React, Antd, .NET, MySQL and Odata",
    description:
      "A website for the interaction of tourists and travel agencies",
    image: "./TravelAgency.png",
    link: "https://github.com/Jara-Devs/Travel-Agency",
  },
  {
    title: "Matcom Social",
    subtitle: "React, Material UI, go and postgres",
    description: "A social network",
    image: "./social-network.png",
    link: "https://github.com/raudel25/social-network-api",
  },
  {
    title: "Todo App",
    subtitle: "React, Antd, MySQL and .NET",
    description: "A TODO list application",
    image: "./TodoApp.png",
    link: "https://github.com/raudel25/Todo-List-App",
  },
  {
    title: "n-omino",
    subtitle: "Blazor",
    description: "A somewhat peculiar domino game",
    image: "./n-omino.png",
    link: "https://github.com/raudel25/n-omino",
  },
  {
    title: "Expression",
    subtitle: "Blazor and Mathematics",
    description: "A suite of mathematical expressions",
    image: "./Expression.png",
    link: "https://github.com/raudel25/Expression",
  },
  {
    title: "Journal App",
    subtitle: "React, Redux, MySQL and Supabase",
    description: "Learning React",
    image: "./JournalApp.png",
    link: "https://github.com/raudel25/Journal-App",
  },
  {
    title: "Calendar App",
    subtitle: "React, Redux, MySQL and .NET",
    description: "Learning React",
    image: "./CalendarApp.png",
    link: "https://github.com/raudel25/Calendar-App",
  },
];

export const experience = [
  {
    quote:
      "During my studies at the university I have worked as an assistant in the subjects of Algebra and Data Structures and Algorithms",
    image: "uh_logo.jpg",
    name: "Assistant Professor",
    company: "Havana University",
    startDate: "04/2022",
    endDate: "Till Date",
    type: "Partial-time",
    skills: ["Competitive Programming", "Data Structures and Algorithms"],
  },
  {
    quote:
      "Work as a mobile developer exploring a new world of software development",
    image: "business_seed_logo.jpg",
    name: "Mobile Developer",
    company: "Business Seed",
    startDate: "02/2024",
    endDate: "Till Date",
    type: "Full-time",
    skills: ["Dart", "Flutter"],
  },
  {
    quote:
      "I worked as a full stack developer developing my back-end and front-end skills",
    image: "./jobs2live_logo.jpg",
    name: "Full Stack Developer",
    company: "jobs2live",
    startDate: "09/2023",
    endDate: "01/2024",
    type: "Full-time",
    skills: ["TypeScript", "React", ".NET", "MySQL"],
  },
];

export const skills = [
  { text: "C#", icon: "https://skillicons.dev/icons?i=cs" },
  { text: "Python", icon: "https://skillicons.dev/icons?i=python" },
  { text: "Rust", icon: "https://skillicons.dev/icons?i=rust" },
  { text: "C", icon: "https://skillicons.dev/icons?i=c" },
  { text: "C++", icon: "https://skillicons.dev/icons?i=cpp" },
  { text: "Javascript", icon: "https://skillicons.dev/icons?i=js" },
  { text: "Typescript", icon: "https://skillicons.dev/icons?i=ts" },
  { text: "Dart", icon: "https://skillicons.dev/icons?i=dart" },
  { text: "Go", icon: "https://skillicons.dev/icons?i=go" },
  // "Competitive Programming",
  // "Data Structures and Algorithms",
  { text: "React", icon: "https://skillicons.dev/icons?i=react" },
  { text: "Flutter", icon: "https://skillicons.dev/icons?i=flutter" },
  { text: ".NET", icon: "https://skillicons.dev/icons?i=dotnet" },
  { text: "MySQL", icon: "https://skillicons.dev/icons?i=mysql" },
  { text: "HTML", icon: "https://skillicons.dev/icons?i=html" },
  { text: "CSS", icon: "https://skillicons.dev/icons?i=css" },
  { text: "SASS", icon: "https://skillicons.dev/icons?i=sass" },
  { text: "Git", icon: "https://skillicons.dev/icons?i=git" },
  { text: "Github", icon: "https://skillicons.dev/icons?i=github" },
  { text: "Linux", icon: "https://skillicons.dev/icons?i=linux" },
  { text: "Latex", icon: "https://skillicons.dev/icons?i=latex" },
  { text: "Redux", icon: "https://skillicons.dev/icons?i=redux" },
  { text: "Supabase", icon: "https://skillicons.dev/icons?i=supabase" },
  { text: "Docker", icon: "https://skillicons.dev/icons?i=docker" },
];
