export const projects = [
  {
    title: "Travel Agency",
    subtitle: "React, Antd, .NET, MySQL and Odata",
    description:
      "A website for the interaction of tourists and travel agencies",
    image: "./TravelAgency.png",
    sourceUrl: "https://github.com/ARJ-Code/Travel-Agency",
    liveUrl: "https://travel-agency-client.onrender.com/",
  },
  {
    title: "Teslo shop",
    subtitle: "React, Next, Tailwind CSS ans PostgreSQL",
    description: "A ecommerce",
    image: "./teslo-shop.png",
    sourceUrl: "https://github.com/raudel25/teslo-shop",
    liveUrl: "https://teslo-shop-phi.vercel.app/",
  },
  {
    title: "Matcom Social",
    subtitle: "React, Material UI, Go and PostgreSQL",
    description: "A social network",
    image: "./social-network.png",
    sourceUrl: "https://github.com/raudel25/social-network-api",
    liveUrl: "https://social-network-client-6f8h.onrender.com",
  },
  {
    title: "Expression",
    subtitle: "Blazor, Boostrap and Mathematics",
    description: "A suite of mathematical expressions",
    image: "./Expression.png",
    sourceUrl: "https://github.com/raudel25/Expression",
    liveUrl: "https://expression-dxtu.onrender.com",
  },
  {
    title: "Journal App",
    subtitle: "React, Redux and Supabase",
    description: "Learning React",
    image: "./JournalApp.png",
    sourceUrl: "https://github.com/raudel25/Journal-App",
    liveUrl: "https://raudel25.github.io/Journal-App/",
  },
  {
    title: "Calendar App",
    subtitle: "React, Redux, PostgreSQL and .NET",
    description: "Learning React",
    image: "./CalendarApp.png",
    sourceUrl: "https://github.com/raudel25/Calendar-App",
    liveUrl: "https://calendar-app-44rm.onrender.com/",
  },
  {
    title: "Chess",
    subtitle: "Python and pygame",
    description: "A chess game",
    image: "./chess.png",
    sourceUrl: "https://github.com/raudel25/Chess",
  },
];

export const experience = [
  {
    quote:
      "During my studies at the university I have worked as an assistant in the subjects of Algebra and Data Structures and Algorithms",
    image: "uh_logo.jpg",
    name: "Assistant Professor",
    company: "Havana University",
    startDate: "04/2022",
    endDate: "Till Date",
    type: "Partial-time",
    skills: ["Competitive Programming", "Data Structures and Algorithms"],
  },
  {
    quote:
      "Work as a mobile developer exploring a new world of software development",
    image: "business_seed_logo.jpg",
    name: "Mobile Developer",
    company: "Business Seed",
    startDate: "02/2024",
    endDate: "Till Date",
    type: "Full-time",
    skills: ["Dart", "Flutter"],
  },
  {
    quote:
      "I worked as a full stack developer developing my back-end and front-end skills",
    image: "./jobs2live_logo.jpg",
    name: "Full Stack Developer",
    company: "jobs2live",
    startDate: "09/2023",
    endDate: "01/2024",
    type: "Full-time",
    skills: ["TypeScript", "React", ".NET", "MySQL"],
  },
];

export const skills = [
  { text: "C#", icon: "https://skillicons.dev/icons?i=cs" },
  { text: "Python", icon: "https://skillicons.dev/icons?i=python" },
  { text: "Rust", icon: "https://skillicons.dev/icons?i=rust" },
  { text: "C", icon: "https://skillicons.dev/icons?i=c" },
  { text: "C++", icon: "https://skillicons.dev/icons?i=cpp" },
  { text: "Javascript", icon: "https://skillicons.dev/icons?i=js" },
  { text: "Typescript", icon: "https://skillicons.dev/icons?i=ts" },
  { text: "Dart", icon: "https://skillicons.dev/icons?i=dart" },
  { text: "Go", icon: "https://skillicons.dev/icons?i=go" },
  { text: "React", icon: "https://skillicons.dev/icons?i=react" },
  { text: "Next", icon: "https://skillicons.dev/icons?i=next" },
  { text: "Flutter", icon: "https://skillicons.dev/icons?i=flutter" },
  { text: ".NET", icon: "https://skillicons.dev/icons?i=dotnet" },
  { text: "MySQL", icon: "https://skillicons.dev/icons?i=mysql" },
  { text: "PostgreSQL", icon: "https://skillicons.dev/icons?i=postgresql" },
  { text: "HTML", icon: "https://skillicons.dev/icons?i=html" },
  { text: "CSS", icon: "https://skillicons.dev/icons?i=css" },
  { text: "SASS", icon: "https://skillicons.dev/icons?i=sass" },
  { text: "Tailwind CSS", icon: "https://skillicons.dev/icons?i=tailwind" },
  { text: "Git", icon: "https://skillicons.dev/icons?i=git" },
  { text: "Github", icon: "https://skillicons.dev/icons?i=github" },
  { text: "Linux", icon: "https://skillicons.dev/icons?i=linux" },
  { text: "Latex", icon: "https://skillicons.dev/icons?i=latex" },
  { text: "Redux", icon: "https://skillicons.dev/icons?i=redux" },
  { text: "Supabase", icon: "https://skillicons.dev/icons?i=supabase" },
  { text: "Docker", icon: "https://skillicons.dev/icons?i=docker" },
];
